source 'http://rubygems.org'

ruby '2.2.4'

gem 'bundler', '>= 1.8.4'
gem 'rake'

gem 'sinatra', '~> 1.4.7', require: 'sinatra/base'
gem 'sequel', '~> 4.0'
gem 'mysql2', '~> 0.4.4'
gem 'thin', '~> 1.6.4'
gem 'concurrent-ruby', '~> 1.0.1', require: false

group :development do
  gem 'pry'
  # gem 'sinatra-contrib'
end
